export const ADD_TEST_SUCCESS = 'ADD_TEST_SUCCESS';

export const START_GAME_SUCCESS = 'START_GAME_SUCCESS';
export const END_GAME_SUCCESS = 'END_GAME_SUCCESS';

export const START_ROUND_SUCCESS = 'START_ROUND_SUCCESS';
export const END_ROUND_SUCCESS = 'END_ROUND_SUCCESS';
export const PAUSE_ROUND_SUCCESS = 'PAUSE_ROUND_SUCCESS';
