export const ADD_TEST_SUCCESS = 'ADD_TEST_SUCCESS';

export const START_GAME_SUCCESS = 'START_GAME_SUCCESS';
export const END_GAME_SUCCESS = 'END_GAME_SUCCESS';

export const START_ROUND_SUCCESS = 'START_ROUND_SUCCESS';
export const END_ROUND_SUCCESS = 'END_ROUND_SUCCESS';
export const PAUSE_ROUND_SUCCESS = 'PAUSE_ROUND_SUCCESS';

export const NEXT_PHASE_SUCCESS = 'NEXT_PHASE_SUCCESS';
export const RESET_PHASE_SUCCESS = 'RESET_PHASE_SUCCESS';

export const ADD_BLUE_SUCCESS = 'ADD_BLUE_SUCCESS';
export const ADD_RED_SUCCESS = 'ADD_RED_SUCCESS';
export const SWITCH_TEAM_SUCCESS = 'SWITCH_TEAM_SUCCESS';

export const NEXT_CARD_SUCCESS = 'NEXT_CARD_SUCCESS';

export const TICK_SUCCESS = 'TICK_SUCCESS';
export const TIMER_RESET_SUCCESS = 'TIMER_RESET_SUCCESS';
export const TIMER_STOP_SUCCESS = 'TIMER_STOP_SUCCESS';
export const TIMER_START_SUCCESS = 'TIMER_START_SUCCESS';

export const RANDOM_DECK_SUCCESS = 'RANDOM_DECK_SUCCESS';
export const SHIFT_DECK_SUCCESS = 'SHIFT_DECK_SUCCESS';
